# Generated by Django 5.1.6 on 2025-02-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
